language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-xenial -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - make INSTALL_ROOT=appdir install ; find appdir/

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/SortPixels_Qt -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/SortPixels_Qt -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./APPNAME*.AppImage https://transfer.sh/SortPixels_Qt-git.$(git rev-parse --short HEAD)-x86_64.AppImage